# Assignment is at the bottom! 

# Assignment 

## 1. Use your own dataset (`Heart.csv` is acceptable), create a train and a test set,  and build 2 models: Logistic Regression and Decision Tree (shallow). Compare the test results using `classification_report` and `confusion_matrix`. Explain which algorithm is optimal
## 2. Repeat 1. but let the Decision Tree be much deeper to allow over-fitting. Compare the two models' test results again, and explain which is optimal

In [319]:
import matplotlib.pyplot as plt
%matplotlib inline
plt.rcParams['figure.figsize'] = 20, 10
import pandas as pd
import numpy as np
import os

from sklearn.linear_model import LogisticRegression
from pylab import rcParams
rcParams['figure.figsize'] = 20, 10

from sklearn.tree import DecisionTreeClassifier

from sklearn.linear_model import LogisticRegression as Model
from sklearn.metrics import (accuracy_score, 
                             classification_report, 
                             confusion_matrix, auc, roc_curve
                            )
from sklearn import linear_model, metrics
from sklearn.model_selection import train_test_split

#bringing in data 

filename = "/Users/sanmirkem/Desktop/mlnn-personal/data/Heart.csv"
heart_data = pd.read_csv(filename)
heart_data

Unnamed: 0  Age  Sex     ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  \
0             1   63    1       typical     145   233    1        2    150   
1             2   67    1  asymptomatic     160   286    0        2    108   
2             3   67    1  asymptomatic     120   229    0        2    129   
3             4   37    1    nonanginal     130   250    0        0    187   
4             5   41    0    nontypical     130   204    0        2    172   
..          ...  ...  ...           ...     ...   ...  ...      ...    ...   
298         299   45    1       typical     110   264    0        0    132   
299         300   68    1  asymptomatic     144   193    1        0    141   
300         301   57    1  asymptomatic     130   131    0        0    115   
301         302   57    0    nontypical     130   236    0        2    174   
302         303   38    1    nonanginal     138   175    0        0    173   

     ExAng  Oldpeak  Slope   Ca        Thal  AHD  
0        0      2.3      3  0.0       fixed   No  
1        1      1.5      2  3.0      normal  Yes  
2        1      2.6      2  2.0  reversable  Yes  
3        0      3.5      3  0.0      normal   No  
4        0      1.4      1  0.0      normal   No  
..     ...      ...    ...  ...         ...  ...  
298      0      1.2      2  0.0  reversable  Yes  
299      0      3.4      2  2.0  reversable  Yes  
300      1      1.2      2  1.0  reversable  Yes  
301      0      0.0      2  1.0      normal  Yes  
302      0      0.0      1  NaN      normal   No  

[303 rows x 15 columns]

In [270]:
heart_data['AHD']=heart_data['AHD'].map({'Yes':1,'No':0})
heart_data.head()

Unnamed: 0  Age  Sex     ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  \
0           1   63    1       typical     145   233    1        2    150   
1           2   67    1  asymptomatic     160   286    0        2    108   
2           3   67    1  asymptomatic     120   229    0        2    129   
3           4   37    1    nonanginal     130   250    0        0    187   
4           5   41    0    nontypical     130   204    0        2    172   

   ExAng  Oldpeak  Slope   Ca        Thal  AHD  
0      0      2.3      3  0.0       fixed    0  
1      1      1.5      2  3.0      normal    1  
2      1      2.6      2  2.0  reversable    1  
3      0      3.5      3  0.0      normal    0  
4      0      1.4      1  0.0      normal    0

In [271]:
heart_data.drop(heart_data.columns[0], axis = 1, inplace = True)
heart_data.head()

Age  Sex     ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  ExAng  Oldpeak  \
0   63    1       typical     145   233    1        2    150      0      2.3   
1   67    1  asymptomatic     160   286    0        2    108      1      1.5   
2   67    1  asymptomatic     120   229    0        2    129      1      2.6   
3   37    1    nonanginal     130   250    0        0    187      0      3.5   
4   41    0    nontypical     130   204    0        2    172      0      1.4   

   Slope   Ca        Thal  AHD  
0      3  0.0       fixed    0  
1      2  3.0      normal    1  
2      2  2.0  reversable    1  
3      3  0.0      normal    0  
4      1  0.0      normal    0

In [320]:
heart_data.drop(columns=['ChestPain','Thal'], axis=1,inplace=True)
heart_data.head()

Unnamed: 0  Age  Sex  RestBP  Chol  Fbs  RestECG  MaxHR  ExAng  Oldpeak  \
0           1   63    1     145   233    1        2    150      0      2.3   
1           2   67    1     160   286    0        2    108      1      1.5   
2           3   67    1     120   229    0        2    129      1      2.6   
3           4   37    1     130   250    0        0    187      0      3.5   
4           5   41    0     130   204    0        2    172      0      1.4   

   Slope   Ca  AHD  
0      3  0.0   No  
1      2  3.0  Yes  
2      2  2.0  Yes  
3      3  0.0   No  
4      1  0.0   No

In [273]:
HD = heart_data.AHD.value_counts()[0]
No_HD = heart_data.AHD.value_counts()[1]
print('Heart Disease: ', HD)
print('No Heart Disease: ', No_HD)

Heart Disease:  164
No Heart Disease:  139


In [274]:
#checking for NAs
heart_data.isnull().sum()
heart_data = heart_data.dropna(axis=0,subset=['Ca'])

In [275]:
heart_data.isnull().sum()

Age        0
Sex        0
RestBP     0
Chol       0
Fbs        0
RestECG    0
MaxHR      0
ExAng      0
Oldpeak    0
Slope      0
Ca         0
AHD        0
dtype: int64

In [277]:
# Splitting data into testing and training 
x = heart_data.drop(['AHD'], axis = 1)
y = heart_data.AHD.values

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

In [291]:
# conducting logistic regression 

heart_data.replace([np.inf, -np.inf], np.nan, inplace=True)
logistic_regression_model = LogisticRegression()
logistic_regression_model.fit(x_train, y_train) 
logistic_predictions =logistic_regression_model.predict(x_test)
logistic_regression_accuracy=accuracy_score(y_test, logistic_predictions)*100


print('Logistic Regression Testing Accuracy: ',logistic_regression_accuracy)

Logistic Regression Testing Accuracy:  73.33333333333333


/Users/sanmirkem/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [293]:
print(classification_report(y_test, logistic_predictions))

              precision    recall  f1-score   support

           0       0.69      0.83      0.76        30
           1       0.79      0.63      0.70        30

    accuracy                           0.73        60
   macro avg       0.74      0.73      0.73        60
weighted avg       0.74      0.73      0.73        60



In [294]:
confusion_matrix(y_test, logistic_predictions)

array([[25,  5],
       [11, 19]])

In [288]:
clf = DecisionTreeClassifier(criterion='entropy') 
clf.fit(x_train, y_train)

# making predictions
clf_pred = clf.predict(x_test) # Test the prediction accurracy of the model
accuracy_score(y_test, clf_pred)

0.75

In [295]:
print(classification_report(y_test, clf_pred))

              precision    recall  f1-score   support

           0       0.76      0.73      0.75        30
           1       0.74      0.77      0.75        30

    accuracy                           0.75        60
   macro avg       0.75      0.75      0.75        60
weighted avg       0.75      0.75      0.75        60



In [297]:
confusion_matrix(y_test, clf_pred)
#After running our models, we see that the decision tree outperformed the logistic regression in some areas. 
# For e.g., our confusion matrix shows the decision tree predicted more1's compared to the
                                #logisitic model.
# Despite having a lower recall percentage of 0's compared to the Logistic model
                #the decision had a smaller disparity in f1-score between the health disease diagnosis (AHD). 
    #I assume this is a good thing?

array([[22,  8],
       [ 7, 23]])

In [314]:
clf_v2 = DecisionTreeClassifier(max_depth=11) 
clf_v2.fit(x_train, y_train)

# making predictions
clf_pred_v2 = clf_v2.predict(x_test) # Test the prediction accurracy of the model
accuracy_score(y_test, clf_pred_v2)

0.8333333333333334

In [316]:
print(classification_report(y_test, clf_pred_v2))

              precision    recall  f1-score   support

           0       0.83      0.83      0.83        30
           1       0.83      0.83      0.83        30

    accuracy                           0.83        60
   macro avg       0.83      0.83      0.83        60
weighted avg       0.83      0.83      0.83        60



In [321]:
confusion_matrix(y_test, clf_pred_v2)

array([[25,  5],
       [ 5, 25]])

In [ ]:
#I believe this model (when allowing for over fitting) is more optimal. 
            #It descreased the gap between incorrect 0's/1's predictions.